# Generated by Django 2.1.7 on 2019-02-21 10:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190220_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='post_photo'),
        ),
    ]
